---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-forum-api-product-ordering-management
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tm-forum-api-product-ordering-management
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tm-forum-api-product-ordering-management
    spec:
      containers:
        - env:
            - name: ENDPOINTS_ALL_PORT
              value: "9090"
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: MICRONAUT_METRICS_ENABLED
              value: "true"
            - name: ENDPOINTS_HEALTH_ENABLED
              value: "true"
            - name: MICRONAUT_GENERAL_SERVER_HOST
              value: "http://tm-forum-api-product-ordering-management:8081"
            - name: LOGGER_LEVELS_ROOT
              value: INFO
            - name: MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE
              value: "1000"
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE
              value: 2s
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS
              value: 2s
            - name: MICRONAUT_HTTP_SERVICES_READ_TIMEOUT
              value: 30s
            - name: MICRONAUT_HTTP_SERVICES_NGSI_PATH
              value: ngsi-ld/v1
            - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
              value: http://scorpio:1026
            - name: GENERAL_BASEPATH
              value: /tmf-api/productOrderingManagement/v4
            - name: GENERAL_CONTEXT_URL
              value: https://raw.githubusercontent.com/wistefan/edc-dsc/refs/heads/init/odrl-context.jsonld
          image: quay.io/fiware/tmforum-product-ordering-management:1.4.0
          imagePullPolicy: Always
          name: product-ordering-management
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: http-health
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: tm-forum-api-product-ordering-management
  labels:
    app.kubernetes.io/name: tm-forum-api-product-ordering-management
spec:
  type: LoadBalancer
  ports:
    - port: 6081
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tm-forum-api-product-ordering-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-forum-api-product-catalog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tm-forum-api-product-catalog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tm-forum-api-product-catalog
    spec:
      containers:
        - env:
            - name: ENDPOINTS_ALL_PORT
              value: "9090"
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: MICRONAUT_METRICS_ENABLED
              value: "true"
            - name: ENDPOINTS_HEALTH_ENABLED
              value: "true"
            - name: LOGGER_LEVELS_ROOT
              value: TRACE
            - name: MICRONAUT_GENERAL_SERVER_HOST
              value: "http://tm-forum-api-product-catalog:8082"
            - name: MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE
              value: "1000"
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE
              value: 2s
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS
              value: 2s
            - name: MICRONAUT_HTTP_SERVICES_READ_TIMEOUT
              value: 30s
            - name: MICRONAUT_HTTP_SERVICES_NGSI_PATH
              value: ngsi-ld/v1
            - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
              value: http://scorpio:1026
            - name: GENERAL_BASEPATH
              value: /tmf-api/productCatalogManagement/v4
            - name: GENERAL_CONTEXT_URL
              value: https://raw.githubusercontent.com/wistefan/edc-dsc/refs/heads/init/odrl-context.jsonld
          image: quay.io/fiware/tmforum-product-catalog:1.4.0
          imagePullPolicy: IfNotPresent
          name: tm-forum-api-product-catalog
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: http-health
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: tm-forum-api-product-catalog
  labels:
    app.kubernetes.io/name: tm-forum-api-product-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 6082
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tm-forum-api-product-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-forum-api-party-catalog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tm-forum-api-party-catalog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tm-forum-api-party-catalog
    spec:
      containers:
        - env:
            - name: ENDPOINTS_ALL_PORT
              value: "9090"
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: MICRONAUT_METRICS_ENABLED
              value: "true"
            - name: ENDPOINTS_HEALTH_ENABLED
              value: "true"
            - name: LOGGER_LEVELS_ROOT
              value: INFO
            - name: MICRONAUT_GENERAL_SERVER_HOST
              value: "http://tm-forum-api-party-catalog:8083"
            - name: MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE
              value: "1000"
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE
              value: 2s
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS
              value: 2s
            - name: MICRONAUT_HTTP_SERVICES_READ_TIMEOUT
              value: 30s
            - name: MICRONAUT_HTTP_SERVICES_NGSI_PATH
              value: ngsi-ld/v1
            - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
              value: http://scorpio:1026
            - name: GENERAL_BASEPATH
              value: /tmf-api/party/v4
          image: quay.io/fiware/tmforum-party-catalog:1.4.0
          imagePullPolicy: IfNotPresent
          name: tm-forum-api-party-catalog
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: http-health
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: tm-forum-api-party-catalog
  labels:
    app.kubernetes.io/name: tm-forum-api-party-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 6083
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tm-forum-api-party-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-forum-api-service-catalog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tm-forum-api-service-catalog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tm-forum-api-service-catalog
    spec:
      containers:
        - env:
            - name: ENDPOINTS_ALL_PORT
              value: "9090"
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: MICRONAUT_METRICS_ENABLED
              value: "true"
            - name: ENDPOINTS_HEALTH_ENABLED
              value: "true"
            - name: MICRONAUT_GENERAL_SERVER_HOST
              value: "http://tm-forum-api-service-catalog:8084"
            - name: LOGGER_LEVELS_ROOT
              value: INFO
            - name: MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE
              value: "1000"
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE
              value: 2s
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS
              value: 2s
            - name: MICRONAUT_HTTP_SERVICES_READ_TIMEOUT
              value: 30s
            - name: MICRONAUT_HTTP_SERVICES_NGSI_PATH
              value: ngsi-ld/v1
            - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
              value: http://scorpio:1026
            - name: GENERAL_BASEPATH
              value: /tmf-api/serviceCatalogManagement/v4
          image: quay.io/fiware/tmforum-service-catalog:1.4.0
          imagePullPolicy: IfNotPresent
          name: tm-forum-api-service-catalog
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: http-health
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: tm-forum-api-service-catalog
  labels:
    app.kubernetes.io/name: tm-forum-api-service-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 6084
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tm-forum-api-service-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-forum-api-agreement
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tm-forum-api-agreement
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tm-forum-api-agreement
    spec:
      containers:
        - env:
            - name: ENDPOINTS_ALL_PORT
              value: "9090"
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: MICRONAUT_METRICS_ENABLED
              value: "true"
            - name: ENDPOINTS_HEALTH_ENABLED
              value: "true"
            - name: MICRONAUT_GENERAL_SERVER_HOST
              value: "http://tm-forum-api-agreement:8086"
            - name: LOGGER_LEVELS_ROOT
              value: INFO
            - name: MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE
              value: "1000"
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE
              value: 2s
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS
              value: 2s
            - name: MICRONAUT_HTTP_SERVICES_READ_TIMEOUT
              value: 30s
            - name: MICRONAUT_HTTP_SERVICES_NGSI_PATH
              value: ngsi-ld/v1
            - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
              value: http://scorpio:1026
            - name: GENERAL_BASEPATH
              value: /tmf-api/agreementManagement/v4
            - name: GENERAL_CONTEXT_URL
              value: https://raw.githubusercontent.com/wistefan/edc-dsc/refs/heads/init/odrl-context.jsonld
          image: quay.io/fiware/tmforum-agreement:1.4.0
          imagePullPolicy: Always
          name: tm-forum-api-agreement
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: http-health
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: tm-forum-api-agreement
  labels:
    app.kubernetes.io/name: tm-forum-api-agreement
spec:
  type: LoadBalancer
  ports:
    - port: 6086
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tm-forum-api-agreement
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-forum-api-quote
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tm-forum-api-quote
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tm-forum-api-quote
    spec:
      containers:
        - env:
            - name: ENDPOINTS_ALL_PORT
              value: "9090"
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: MICRONAUT_METRICS_ENABLED
              value: "true"
            - name: ENDPOINTS_HEALTH_ENABLED
              value: "true"
            - name: MICRONAUT_GENERAL_SERVER_HOST
              value: "http://tm-forum-api-quote:8087"
            - name: LOGGER_LEVELS_ROOT
              value: INFO
            - name: MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE
              value: "1000"
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE
              value: 2s
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS
              value: 2s
            - name: MICRONAUT_HTTP_SERVICES_READ_TIMEOUT
              value: 30s
            - name: MICRONAUT_HTTP_SERVICES_NGSI_PATH
              value: ngsi-ld/v1
            - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
              value: http://scorpio:1026
            - name: GENERAL_BASEPATH
              value: /tmf-api/quote/v4
            - name: GENERAL_CONTEXT_URL
              value: https://raw.githubusercontent.com/wistefan/edc-dsc/refs/heads/init/odrl-context.jsonld
          image: quay.io/fiware/tmforum-quote:1.4.0
          imagePullPolicy: Always
          name: tm-forum-api-quote
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: http-health
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: tm-forum-api-quote
  labels:
    app.kubernetes.io/name: tm-forum-api-quote
spec:
  type: LoadBalancer
  ports:
    - port: 6087
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tm-forum-api-quote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-forum-api-usage-management
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tm-forum-api-usage-management
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tm-forum-api-usage-management
    spec:
      containers:
        - env:
            - name: ENDPOINTS_ALL_PORT
              value: "9090"
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: MICRONAUT_METRICS_ENABLED
              value: "true"
            - name: ENDPOINTS_HEALTH_ENABLED
              value: "true"
            - name: MICRONAUT_GENERAL_SERVER_HOST
              value: "http://tm-forum-api-usage-management:8088"
            - name: LOGGER_LEVELS_ROOT
              value: INFO
            - name: MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE
              value: "1000"
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE
              value: 2s
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS
              value: 2s
            - name: MICRONAUT_HTTP_SERVICES_READ_TIMEOUT
              value: 30s
            - name: MICRONAUT_HTTP_SERVICES_NGSI_PATH
              value: ngsi-ld/v1
            - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
              value: http://scorpio:1026
            - name: GENERAL_BASEPATH
              value: /tmf-api/usageManagement/v4
          image: quay.io/fiware/tmforum-usage-management:1.4.0
          imagePullPolicy: Always
          name: tm-forum-api-quote
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: http-health
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: tm-forum-api-usage-management
  labels:
    app.kubernetes.io/name: tm-forum-api-usage-management
spec:
  type: LoadBalancer
  ports:
    - port: 6088
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tm-forum-api-usage-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-forum-api-product-inventory
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tm-forum-api-product-inventory
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tm-forum-api-product-inventory
    spec:
      containers:
        - env:
            - name: ENDPOINTS_ALL_PORT
              value: "9090"
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: MICRONAUT_METRICS_ENABLED
              value: "true"
            - name: ENDPOINTS_HEALTH_ENABLED
              value: "true"
            - name: MICRONAUT_GENERAL_SERVER_HOST
              value: "http://tm-forum-api-product-inventory:8089"
            - name: LOGGER_LEVELS_ROOT
              value: INFO
            - name: MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE
              value: "1000"
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE
              value: 2s
            - name: MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS
              value: 2s
            - name: MICRONAUT_HTTP_SERVICES_READ_TIMEOUT
              value: 30s
            - name: MICRONAUT_HTTP_SERVICES_NGSI_PATH
              value: ngsi-ld/v1
            - name: MICRONAUT_HTTP_SERVICES_NGSI_URL
              value: http://scorpio:1026
            - name: GENERAL_BASEPATH
              value: /tmf-api/productInventory/v4
            - name: GENERAL_CONTEXT_URL
              value: https://raw.githubusercontent.com/wistefan/edc-dsc/refs/heads/init/odrl-context.jsonld
          image: quay.io/fiware/tmforum-product-inventory:1.4.0
          imagePullPolicy: Always
          name: product-inventory
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: http-health
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: tm-forum-api-product-inventory
  labels:
    app.kubernetes.io/name: tm-forum-api-product-inventory
spec:
  type: LoadBalancer
  ports:
    - port: 6089
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tm-forum-api-product-inventory
---