apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edc.fullname" . }}-controlplane
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "edc.name" . }}-dataplane
    {{ include "edc.labels" . | nindent 4 }}
data:
  dataspaceconnector-configuration.properties: |
    {{ .Values.configMap | nindent 4 }}