apiVersion: v1
kind: Service
metadata:
  name: {{ include "edc.fullname" . }}-controlplane
  namespace: {{ $.Release.Namespace | quote }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "edc.name" . }}-controlplane
    {{ include "edc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.version.port }}
      targetPort: http-version
      protocol: TCP
      name: http-version
    - port: {{ .Values.service.protocol.port }}
      targetPort: http-protocol
      protocol: TCP
      name: http-protocol
    - port: {{ .Values.service.catalog.port }}
      targetPort: http-catalog
      protocol: TCP
      name: http-catalog
    - port: {{ .Values.service.management.port }}
      targetPort: http-management
      protocol: TCP
      name: http-management
    - port: {{ .Values.service.control.port }}
      targetPort: http-control
      protocol: TCP
      name: http-control
    - port: 8687
      targetPort: http-tck
      protocol: TCP
      name: http-tck
  selector:
    app.kubernetes.io/name: {{ include "edc.name" . }}-controlplane
    app.kubernetes.io/instance: {{ .Release.Name }}