openapi: 3.0.3
info:
  description: ODRL PAP
  title: ODRL PAP
  version: 1.0.0
servers:
- url: /
tags:
- description: Set of endpoints to manage policies for a specific service
  name: Service
- description: Set of endpoints to manage policies for the main policy
  name: Policy
- description: Set of endpoint intended to support integration with frontends
  name: UI
paths:
  /service:
    get:
      operationId: getServices
      parameters:
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - explode: true
        in: query
        name: pageSize
        required: false
        schema:
          default: 25
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceList'
          description: The services
      summary: Get all services and the path to their policy
      tags:
      - Service
      x-accepts:
      - application/json
    post:
      operationId: createService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceCreate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyPath'
          description: The policy path
        "409":
          description: Service already exists
      summary: Create a new service to group policies
      tags:
      - Service
      x-content-type: application/json
      x-accepts:
      - application/json
  /service/{service-id}:
    delete:
      operationId: deleteService
      parameters:
      - explode: false
        in: path
        name: service-id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Successfully deleted
      summary: Delete the service with the given id and all policies below
      tags:
      - Service
      x-accepts:
      - application/json
    get:
      operationId: getService
      parameters:
      - explode: false
        in: path
        name: service-id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
          description: The service
        "404":
          description: No such service exists
      summary: Get the service with the given id
      tags:
      - Service
      x-accepts:
      - application/json
  /service/{service-id}/policy:
    get:
      operationId: getServicePolicies
      parameters:
      - explode: false
        in: path
        name: service-id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - explode: true
        in: query
        name: pageSize
        required: false
        schema:
          default: 25
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyList'
          description: Successfully retrieved the policis.
        "404":
          description: No such policy exists
      summary: Get the policies in the ODRL-Format under the service-id
      tags:
      - Service
      x-accepts:
      - application/json
    post:
      operationId: createServicePolicy
      parameters:
      - explode: false
        in: path
        name: service-id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OdrlPolicyJson'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: The rego policy
          headers:
            Location:
              description: location of the created policy
              explode: false
              schema:
                type: string
              style: simple
      summary: Creates a new policy from the given odrl-json under the service-id
      tags:
      - Service
      x-content-type: application/json
      x-accepts:
      - text/plain
  /service/{service-id}/policy/{id}:
    delete:
      operationId: deleteServicePolicyById
      parameters:
      - explode: false
        in: path
        name: service-id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      responses:
        "204":
          description: Policy was successfully removed.
        "404":
          description: No such policy exists
      summary: Delete the given policy under the service-id.
      tags:
      - Service
      x-accepts:
      - application/json
    get:
      operationId: getServicePolicyById
      parameters:
      - explode: false
        in: path
        name: service-id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
          description: Successfully retrieved the policy.
        "404":
          description: No such policy exists
      summary: Return the given policy by its ID under the service-id.
      tags:
      - Service
      x-accepts:
      - application/json
    put:
      operationId: createServicePolicyWithId
      parameters:
      - explode: false
        in: path
        name: service-id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OdrlPolicyJson'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: The rego policy
          headers:
            Location:
              description: location of the created policy
              explode: false
              schema:
                type: string
              style: simple
        "409":
          description: Should be returned in case the policy is not allowed to be
            modified
      summary: Creates or overwrites the given policy under the service-id.
      tags:
      - Service
      x-content-type: application/json
      x-accepts:
      - text/plain
  /service/{service-id}/policy/odrl/{id}:
    delete:
      operationId: deleteServicePolicyByUid
      parameters:
      - explode: false
        in: path
        name: service-id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      responses:
        "204":
          description: Policy was successfully removed.
        "404":
          description: No such policy exists
      summary: Delete the given policy under the service-id.
      tags:
      - Service
      x-accepts:
      - application/json
    get:
      operationId: getServicePolicyByUid
      parameters:
      - explode: false
        in: path
        name: service-id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
          description: Successfully retrieved the policy.
        "404":
          description: No such policy exists
      summary: Return the given policy by its ID under the service-id.
      tags:
      - Service
      x-accepts:
      - application/json
  /policy:
    get:
      operationId: getPolicies
      parameters:
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - explode: true
        in: query
        name: pageSize
        required: false
        schema:
          default: 25
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyList'
          description: Successfully retrieved the policis.
        "404":
          description: No such policy exists
      summary: Get the policies in the ODRL-Format
      tags:
      - Policy
      x-accepts:
      - application/json
    post:
      operationId: createPolicy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OdrlPolicyJson'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: The rego policy
          headers:
            Location:
              description: location of the created policy
              explode: false
              schema:
                type: string
              style: simple
      summary: Creates a new policy from the given odrl-json
      tags:
      - Policy
      x-content-type: application/json
      x-accepts:
      - text/plain
  /policy/{id}:
    delete:
      operationId: deletePolicyById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      responses:
        "204":
          description: Policy was successfully removed.
        "404":
          description: No such policy exists
      summary: Delete the given policy.
      tags:
      - Policy
      x-accepts:
      - application/json
    get:
      operationId: getPolicyById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
          description: Successfully retrieved the policy.
        "404":
          description: No such policy exists
      summary: Return the given policy by its ID.
      tags:
      - Policy
      x-accepts:
      - application/json
    put:
      operationId: createPolicyWithId
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OdrlPolicyJson'
        required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: The rego policy
          headers:
            Location:
              description: location of the created policy
              explode: false
              schema:
                type: string
              style: simple
        "409":
          description: Should be returned in case the policy is not allowed to be
            modified
      summary: Creates or overwrites the given policy.
      tags:
      - Policy
      x-content-type: application/json
      x-accepts:
      - text/plain
  /policy/odrl/{id}:
    delete:
      operationId: deletePolicyByUid
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      responses:
        "204":
          description: Policy was successfully removed.
        "404":
          description: No such policy exists
      summary: Delete the given policy.
      tags:
      - Policy
      x-accepts:
      - application/json
    get:
      operationId: getPolicyByUid
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Uid'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
          description: Successfully retrieved the policy.
        "404":
          description: No such policy exists
      summary: Return the given policy by its ID.
      tags:
      - Policy
      x-accepts:
      - application/json
  /validate:
    post:
      operationId: validatePolicy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidationRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
          description: Validation result
      summary: Validates a policy with a demo request
      tags:
      - UI
      x-content-type: application/json
      x-accepts:
      - application/json
  /mappings:
    get:
      operationId: getMappings
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mappings'
          description: Successfully retrieved the Mappings.
      summary: Gets the supported by the PAP.
      tags:
      - UI
      x-accepts:
      - application/json
components:
  parameters:
    Id:
      explode: false
      in: path
      name: id
      required: true
      schema:
        $ref: '#/components/schemas/Uid'
      style: simple
    ServiceId:
      explode: false
      in: path
      name: service-id
      required: true
      schema:
        type: string
      style: simple
    Page:
      explode: true
      in: query
      name: page
      required: false
      schema:
        default: 0
        type: integer
      style: form
    PageSize:
      explode: true
      in: query
      name: pageSize
      required: false
      schema:
        default: 25
        type: integer
      style: form
  schemas:
    PolicyPath:
      properties:
        policyPath:
          type: string
      type: object
    Id:
      type: string
    ServiceCreate:
      properties:
        id:
          type: string
      type: object
    Service:
      properties:
        id:
          type: string
        policyPath:
          type: string
        policies:
          items:
            $ref: '#/components/schemas/Policy'
          type: array
      type: object
    ServiceList:
      items:
        $ref: '#/components/schemas/ServiceList_inner'
      type: array
    ValidationRequest:
      properties:
        policy:
          additionalProperties: true
          type: object
        testRequest:
          $ref: '#/components/schemas/TestRequest'
      type: object
    TestRequest:
      properties:
        method:
          enum:
          - POST
          - PATCH
          - PUT
          - GET
          - DELETE
          type: string
        host:
          type: string
        path:
          type: string
        protocol:
          enum:
          - https
          type: string
        body:
          type: object
        headers:
          $ref: '#/components/schemas/Headers'
      type: object
    Headers:
      properties:
        accept:
          type: string
        authorization:
          type: string
        content-type:
          type: string
      type: object
    ValidationResponse:
      properties:
        allow:
          description: indicates if the request was allowed by the policy
          type: boolean
        explanation:
          description: "Explanation of the detailed error, in case the policy evaluation\
            \ failed."
          items:
            type: string
          type: array
      type: object
    Mappings:
      description: Mappings available to be used for building policies
      properties:
        actions:
          items:
            $ref: '#/components/schemas/Mapping'
          type: array
        operators:
          items:
            $ref: '#/components/schemas/Mapping'
          type: array
        operands:
          items:
            $ref: '#/components/schemas/Mapping'
          type: array
        rightOperands:
          items:
            $ref: '#/components/schemas/Mapping'
          type: array
        leftOperands:
          items:
            $ref: '#/components/schemas/Mapping'
          type: array
        assignees:
          items:
            $ref: '#/components/schemas/Mapping'
          type: array
        targets:
          items:
            $ref: '#/components/schemas/Mapping'
          type: array
        constraints:
          items:
            $ref: '#/components/schemas/Mapping'
          type: array
      type: object
    Mapping:
      description: A concrete mapping.
      properties:
        name:
          type: string
        description:
          type: string
      type: object
    Policy:
      properties:
        id:
          type: string
        odrl:uid:
          type: string
        odrl:
          type: string
        rego:
          type: string
      type: object
    PolicyList:
      items:
        $ref: '#/components/schemas/Policy'
      type: array
    Uid:
      format: https://datatracker.ietf.org/doc/html/rfc3987
      type: string
    OdrlPolicyJson:
      additionalProperties: true
      type: object
    ServiceList_inner:
      properties:
        id:
          type: string
        policyPath:
          type: string
      type: object

